---
# tasks for installing apache role

- name: Install Apache (httpd)
  become: yes
  yum:
    name: 'httpd'
    state: present
- name: Start/Enable Web Server
  become: yes
  service:
    name: 'httpd'
    state: started 
    enabled: yes
- name: Configure Firewalld
  become: yes
  firewalld:
    service: http
    state: enabled
    permanent: true
  notify:
    - restart-firewall
