---
# MariaDB tasks
- name: Install MariaDB
  become: yes
  yum:
    name: 'mariadb-server'
    state: present
- name: Enable MariaDB
  become: yes
  service:
    name: 'mariadb'   
    enabled: yes
    state: started
