---
- hosts: routers
  gather_facts: false
  connection: local
  tasks: 
  - name: show run
    ios_command:
      commands:
      - sh run
    register: sr_output
  - name: Report Info
    debug:
      var: sr_output
      