---
- hosts: web
  vars: 
    list_of_packages:
    - httpd
    - mariadb-server
    - php
  tasks:
  - name: Install Software
    become: yes
    yum:
      name: "{{ list_of_packages }}" 
      state: present