---
- hosts: all
  become: yes
  tasks:
  - name: "Remove user egoad)"
    user:
      name: egoad
      state: absent
  - name: "Remove user derek"
    user:
      name: derek
      state: absent

- hosts: db
  tasks:
  - name: Remove MariaDB
    become: yes
    yum:
      name: 'mariadb-server'
      state: absent
      autoremove: yes  #trims the dependencies that were installed along with mariadb-server 

- hosts: web
  tasks:
  - name: Remove Apache (httpd)
    become: yes
    yum:
      name: 'httpd'
      state: absent
      autoremove: yes       
  - name: Configure Firewalld
    become: yes
    firewalld:
      service: http
      permanent: true
      state: disabled
    notify:
      - restart-firewall

  handlers:
  - name: restart-firewall
    become: yes
    service:
      name: 'firewalld'
      state: restarted
